[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_etf = "9JNb23fdzmWDt71tWveTQFwdmebP2JDQ6nGrVS63hMdz"

[programs.devnet]
sol_usdc_pool = "58oQChx4yWmvKdwLLZzBi4ChoCc2fqCUWBkwMihLYQo2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kostyambl/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
